version: 2.2.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

environment:
  dotnet_version: 2.2
  matrix:
    - job_name: Windows LATEST amd64
      ARCH: amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Windows 1803 amd64
      ARCH: amd64
      VERSION : 1803
      platform: nanoserver
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Windows 1809 amd64
      ARCH: amd64
      VERSION : 1809
      platform: nanoserver
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    - job_name: Windows 1903
#      VERSION : 1903
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    - job_name: Windows 1909
#      VERSION : 1909
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Linux amd64
      ARCH: amd64
      platform: alpine
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    
matrix:
  fast_finish: true

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1
