version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

image:
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - VERSION : 1803
      image: mcr.microsoft.com/windows/nanoserver:1803
    - VERSION : 1809
      image: mcr.microsoft.com/windows/nanoserver:1809
    - VERSION : 1903
      image: mcr.microsoft.com/windows/nanoserver:1903
    - VERSION : 1909
      image: mcr.microsoft.com/windows/nanoserver:1909
    - ARCH: amd64
    
matrix:
  exclude:
    - image: Ubuntu
      VERSION : 1709
    - image: Ubuntu
      VERSION : 1803
    - image: Ubuntu
      VERSION : 1809
    - image: Ubuntu
      VERSION : 1903
    - image: Ubuntu
      VERSION : 1909

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1