version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

#image:
#  - Visual Studio 2019
#  - Ubuntu

environment:
  matrix:
    - job_name: Windows LATEST
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Windows 1803
      VERSION : 1803
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Windows 1809
      VERSION : 1809
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    - job_name: Windows 1903
#      VERSION : 1903
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#    - job_name: Windows 1909
#      VERSION : 1909
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - job_name: Ubuntu
      ARCH: arm
      ARCHVERSION: arm32v7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - job_name: Ubuntu
      ARCH: amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    
matrix:
  fast_finish: true
#  exclude:
#    - image: Ubuntu
#      VERSION : 1709
#    - image: Ubuntu
#      VERSION : 1803
#    - image: Ubuntu
#      VERSION : 1809
#    - image: Ubuntu
#      VERSION : 1903
#    - image: Ubuntu
#      VERSION : 1909

build_script:
  - ps: ./build.ps1

test_script:
  - ps: ./test.ps1

deploy_script:
  - ps: ./deploy.ps1